stages:
  - name: Build
    steps:
      - runScriptConfig:
          image: maven:3-adoptopenjdk-11
          shellScript: mvn package -DskipTests
  - name: Build Docker with DIND
    steps:
      - publishImageConfig:
          dockerfilePath: ./Dockerfile
          buildContext: .
          tag: docker.dev.folio.org/mod-circulation:vega-964
          pushRemote: true
          registry: docker.dev.folio.org
  - name: Deploy
    steps:
      - applyAppConfig:
          catalogTemplate: p-jqjbc:vega-helmcharts-mod-circulation
          version: 0.1.32
          answers:
            image.repository: docker.dev.folio.org/mod-circulation
            image.tag: vega-964
          targetNamespace: vega
          name: mod-circulation
timeout: 60
notification: {}