package org.folio.circulation.resources.error;

public enum CirculationError {
  INVALID_ITEM,
  INVALID_ITEM_ID,
  INVALID_USER_OR_PATRON_GROUP,
  INVALID_STATUS,
  INVALID_PROXY_RELATIONSHIP,
  INVALID_PICKUP_SERVICE_POINT,

  FAILED_TO_FETCH_ITEM,
  FAILED_TO_FETCH_USER,
  FAILED_TO_FETCH_PROXY_USER,
  FAILED_TO_FETCH_SERVICE_POINT,
  FAILED_TO_FETCH_LOAN,
  FAILED_TO_FETCH_USER_FOR_LOAN,
  FAILED_TO_FETCH_REQUEST_QUEUE,
  FAILED_TO_FETCH_REQUEST_POLICY,
  FAILED_TO_FETCH_TIME_ZONE_CONFIG,

  ITEM_ALREADY_REQUESTED_BY_SAME_USER,
  ITEM_ALREADY_LOANED_TO_SAME_USER,
  USER_IS_INACTIVE,
  USER_IS_BLOCKED_MANUALLY,
  USER_IS_BLOCKED_AUTOMATICALLY,
  REQUESTING_DISALLOWED_BY_REQUEST_POLICY,
  REQUESTING_DISALLOWED_FOR_ITEM
}
