package org.folio.circulation.resources.handlers.error;

public enum CirculationErrorType {
  INVALID_ITEM_ID,
  INVALID_USER_OR_PATRON_GROUP_ID,
  INVALID_PROXY_RELATIONSHIP,
  INVALID_PICKUP_SERVICE_POINT,
  ITEM_DOES_NOT_EXIST,
  ITEM_ALREADY_REQUESTED_BY_SAME_USER,
  ITEM_ALREADY_LOANED_TO_SAME_USER,
  USER_IS_INACTIVE,
  USER_IS_BLOCKED_MANUALLY,
  USER_IS_BLOCKED_AUTOMATICALLY,
  REQUESTING_DISALLOWED_BY_POLICY,
  REQUESTING_DISALLOWED,
  INSUFFICIENT_OVERRIDE_PERMISSIONS,
  ITEM_LIMIT_IS_REACHED,
  ITEM_IS_NOT_LOANABLE
}