package org.folio.circulation.support;

public enum ErrorCode {
  ITEM_NOT_LOANABLE,
  USER_BARCODE_NOT_FOUND,
  ITEM_LIMIT_PATRON_GROUP_MATERIAL_TYPE_LOAN_TYPE,
  ITEM_LIMIT_PATRON_GROUP_MATERIAL_TYPE,
  ITEM_LIMIT_PATRON_GROUP_LOAN_TYPE,
  ITEM_LIMIT_MATERIAL_TYPE_LOAN_TYPE,
  ITEM_LIMIT_MATERIAL_TYPE,
  ITEM_LIMIT_LOAN_TYPE,
  ITEM_HAS_OPEN_LOAN,
  REQUEST_ALREADY_CLOSED,
  REQUEST_NOT_ALLOWED_FOR_PATRON_TITLE_COMBINATION,
  REQUEST_PICKUP_SERVICE_POINT_IS_NOT_ALLOWED,
  SERVICE_POINT_IS_NOT_PICKUP_LOCATION
}
