package org.folio.circulation.support;

public enum ErrorCode {
  ITEM_NOT_LOANABLE,
  USER_BARCODE_NOT_FOUND,
  ITEM_LIMIT_PATRON_GROUP_MATERIAL_TYPE_LOAN_TYPE,
  ITEM_LIMIT_PATRON_GROUP_MATERIAL_TYPE,
  ITEM_LIMIT_PATRON_GROUP_LOAN_TYPE,
  ITEM_LIMIT_MATERIAL_TYPE_LOAN_TYPE,
  ITEM_LIMIT_MATERIAL_TYPE,
  ITEM_LIMIT_LOAN_TYPE,
  ITEM_HAS_OPEN_LOAN,
  REQUEST_ALREADY_CLOSED,
  REQUEST_NOT_ALLOWED_FOR_PATRON_TITLE_COMBINATION,
  REQUEST_PICKUP_SERVICE_POINT_IS_NOT_ALLOWED,
  SERVICE_POINT_IS_NOT_PICKUP_LOCATION,
  REQUEST_LEVEL_IS_NOT_ALLOWED,
  FULFILLMENT_PREFERENCE_IS_NOT_ALLOWED,
  REQUESTER_ALREADY_HAS_LOAN_FOR_INSTANCES_ITEM,
  REQUESTER_ALREADY_HAS_THIS_ITEM_ON_LOAN,
  INSTANCE_HAS_NO_ITEM_ID,
  PAGEABLE_AVAILABLE_ITEM_FOUND,
  USER_CANNOT_BE_PROXY_FOR_THEMSELVES,
  MOVING_REQUEST_TO_THE_SAME_ITEM,
  ALREADY_REQUESTED,
  HOLD_SHELF_REQUESTS_REQUIRE_PICKUP_SERVICE_POINT
}
