
package org.folio.circulation.domain;

public enum EventType {
  ITEM_CHECKED_OUT,
  ITEM_CHECKED_IN,
  ITEM_DECLARED_LOST,
  ITEM_AGED_TO_LOST,
  ITEM_CLAIMED_RETURNED,
  LOAN_DUE_DATE_CHANGED,
  LOAN_CLOSED,
  LOG_RECORD,
  LOAN_RELATED_FEE_FINE_CLOSED,
  ITEM_HELD_FOR_USE_AT_LOCATION,
  ITEM_PICKED_UP_FOR_USE_AT_LOCATION
}
