#%RAML 1.0
title: Age to lost background processes
version: v0.1
protocols: [ HTTP, HTTPS ]
baseUri: http://localhost:9130

documentation:
  - title: Background processes for ageing borrowed items to lost
    content: <b>Background processes for ageing borrowed items to lost</b>

/circulation/scheduled-age-to-lost:
  post:
    responses:
      204:
        description: "The process completed successfully"
      500:
        description: "Internal server error, e.g. due to misconfiguration"
        body:
          text/plain:
            example: "Internal server error, contact administrator"

/circulation/scheduled-age-to-lost-fee-charging:
  post:
    responses:
      204:
        description: "The process completed successfully"
      500:
        description: "Internal server error, e.g. due to misconfiguration"
        body:
          text/plain:
            example: "Internal server error, contact administrator"
