#%RAML 1.0
title: Circulation
version: v0.1
protocols: [ HTTP, HTTPS ]
baseUri: http://localhost:9130

documentation:
  - title: Overdue fine calculation API
    content: <b>Calculate overdue fine and create fee/fine record</b>

types:
  calculate-overdue-fine-response: !include schema/calculate-overdue-fine.json
  errors: !include raml-util/schemas/errors.schema

traits:
  validate: !include raml-util/traits/validation.raml


/circulation:
  /loans/{id}:
    /calculate-overdue-fine:
      post:
        is: [validate]
        body:
        responses:
          200:
            description: "Fee/fine record has been successfully created"
            body:
              application/json:
                type: calculate-overdue-fine-response
          500:
            description: "Internal server error, e.g. due to misconfiguration"
            body:
              text/plain:
                example: "Internal server error, contact administrator"
