#%RAML 0.8
title: Circulation
version: v2.2
protocols: [ HTTP, HTTPS ]
baseUri: http://localhost:9130

documentation:
  - title: Loan Storage API
    content: <b>Storage for loans</b>

schemas:
  - loan.json: !include schema/loan.json
  - loans: !include schema/loans.json

traits:
  - secured: !include raml-util/traits/auth.raml
  - language: !include raml-util/traits/language.raml
  - pageable: !include raml-util/traits/pageable.raml
  - searchable: !include raml-util/traits/searchable.raml

resourceTypes:
  - collection: !include raml-util/rtypes/collection.raml
  - collection-item: !include raml-util/rtypes/item-collection.raml

/circulation:
  /loans:
    displayName: Loans
    type:
      collection:
        exampleCollection: !include examples/loans.json
        exampleItem: !include examples/loan.json
        schemaCollection: loans
        schemaItem: loan.json
    get:
      is: [
        pageable,
        searchable: {description: "by title (using CQL)",
                        example: "userId=\"cf23adf0-61ba-4887-bf82-956c4aae2260\""}
      ]
      responses:
        501:
          description: "Not implemented yet"
    post:
    delete:
      responses:
        204:
          description: "All loans deleted"
        500:
          description: "Internal server error, e.g. due to misconfiguration"
          body:
            text/plain:
              example: "Internal server error, contact administrator"
    /{loanId}:
      type:
        collection-item:
          exampleItem: !include examples/loan.json
          schema: loan.json
      get:
        responses:
          501:
            description: "Not implemented yet"
      put:
        responses:
          501:
            description: "Not implemented yet"
      delete:
        responses:
          501:
            description: "Not implemented yet"
  /loan-rules:
    displayName: Loan rules
    get:
      description: Get the loan rules
      is: [secured]
      responses:
        200:
          body:
            application/json:
              schema: !include schema/loan-rules.json
        500:
          description: "Internal server error"
          body:
            text/plain:
              example: "Internal server error"
    put:
      description: Set the loan rules using a text file
      is: [secured]
      body:
        application/json:
          schema: !include schema/loan-rules-text.json
      responses:
        204:
          description: "Loan rules have been saved."
        422:
          description: "Validation error in the text file."
          body:
            application/json:
              schema: !include schema/loan-rules-error.json
              example: !include examples/loan-rules-error.json
        500:
          description: "Internal server error"
          body:
            text/plain:
              example: "Internal server error"
