#%RAML 1.0
title: End Patron Action Session
version: v0.1
protocols: [ HTTP, HTTPS ]
baseUri: http://localhost:9130

documentation:
  - title: End Patron Action Session API
    content: <b>End patron action session</b>

types:
  errors: !include raml-util/schemas/errors.schema
  end-patron-action-session-requests: !include end-patron-action-session-requests.json

traits:
  validate: !include raml-util/traits/validation.raml

/circulation:
  /end-patron-action-session:
    displayName: End Patron Action Session
    post:
      is: [validate]
      body:
        application/json:
          type: end-patron-action-session-requests
          example: !include examples/end-patron-action-session-requests.json
      responses:
        204:
          description: "Session has been successfully ended"
        500:
          description: "Internal server error"
          body:
            text/plain:
              example: "Internal server error"
