#%RAML 1.0
title: Circulation
version: v0.2
protocols: [ HTTP, HTTPS ]
baseUri: http://localhost:9130

documentation:
  - title: Circulation Business Logic API
    content: <b>API for report generation</b>

types:
  items-in-transit: !include items-in-transit.json
  pick-slips: !include pick-slips-report.json

traits:
  language: !include raml-util/traits/language.raml

resourceTypes:
  collection-get: !include raml-util/rtypes/collection-get.raml

/inventory-reports:
    displayName: Item-based reports
    /items-in-transit:
        type:
          collection-get:
            exampleCollection: !include examples/items-in-transit.json
            schemaCollection: items-in-transit

    /pick-slips:
      /{servicePointId}:
        type:
          collection-get:
            exampleCollection: !include examples/pick-slips-report.json
            schemaCollection: pick-slips
