#%RAML 1.0
title: Circulation
version: v0.1
protocols: [ HTTP, HTTPS ]
baseUri: http://localhost:9130

documentation:
  - title: Loan Anonymization API
    content: <b>Loan Anonymization API</b>

types:
  anonymize-loans-response: !include schema/anonymize-loans-response.json

traits:
  validate: !include raml-util/traits/validation.raml


/loan-anonymization:
    /anonymizeByUserId/{userId}:
      post:
        is: [validate]
        body:
        responses:
          200:
            description: "Chosen loans have been successfully anonymizedd"
            body:
              application/json:
                type: anonymize-loans-response
          500:
            description: "Internal server error, e.g. due to misconfiguration"
            body:
              text/plain:
                example: "Internal server error, contact administrator"
