#%RAML 1.0
title: Print Events
version: v1.0
protocols: [ HTTP, HTTPS ]
baseUri: http://localhost:9130

documentation:
  - title: Print Events API
    content: <b>Api for print events</b>

types:
  print-events-request: !include print-events-request.json
  errors: !include raml-util/schemas/errors.schema

traits:
  validate: !include raml-util/traits/validation.raml

/circulation/print-events:
    post:
      is: [validate]
      description: save a print event log
      body:
        application/json:
          type: print-events-request
      responses:
        201:
          description: "All items have been successfully created or updated"
        409:
          description: "Optimistic locking version conflict"
          body:
            text/plain:
              example: "version error"
        413:
          description: "Payload Too Large"
          body:
            text/plain:
              example: "Payload Too Large"
        422:
          description: "Unprocessable Entity"
          body:
            application/json:
              type: errors
        500:
          description: "Internal server error"
          body:
            text/plain:
              example: "Internal server error"
