#%RAML 1.0
title: Pick Slips
version: v0.3
protocols: [ HTTP, HTTPS ]
baseUri: http://localhost:9130

documentation:
  - title: API for fetching current search slips
    content: <b>API for search slips generation</b>

types:
  search-slips: !include pick-slips-response.json

traits:
  language: !include raml-util/traits/language.raml

resourceTypes:
  collection-get: !include raml-util/rtypes/collection-get.raml

/circulation:
    /search-slips:
      /{servicePointId}:
        type:
          collection-get:
            exampleCollection: !include examples/pick-slips-response.json
            schemaCollection: search-slips
