#%RAML 1.0
title: Staff Slips
version: v0.3
protocols: [ HTTP, HTTPS ]
baseUri: http://localhost:9130

documentation:
  - title: API for fetching current staff slips
    content: <b>API for staff slips generation</b>

types:
  staff-slips: !include staff-slips-response.json

resourceTypes:
  collection-get: !include raml-util/rtypes/collection-get.raml

/circulation:
    /pick-slips:
      /{servicePointId}:
        type:
          collection-get:
            exampleCollection: !include examples/staff-slips-response.json
            schemaCollection: staff-slips
    /search-slips:
      /{servicePointId}:
        type:
          collection-get:
            exampleCollection: !include examples/staff-slips-response.json
            schemaCollection: staff-slips
