package org.folio.circulation.support.http.server;

public enum ErrorCode {
  ITEM_NOT_LOANABLE,
  USER_BARCODE_NOT_FOUND,
  PATRON_BLOCK_LIMIT_REACHED_FOR_PATRON_GROUP_AND_MATERIAL_TYPE_AND_LOAN_TYPE,
  PATRON_BLOCK_LIMIT_REACHED_FOR_PATRON_GROUP_AND_MATERIAL_TYPE,
  PATRON_BLOCK_LIMIT_REACHED_FOR_PATRON_GROUP_AND_LOAN_TYPE,
  PATRON_BLOCK_LIMIT_REACHED_FOR_MATERIAL_TYPE_AND_LOAN_TYPE,
  PATRON_BLOCK_LIMIT_REACHED_FOR_MATERIAL_TYPE,
  PATRON_BLOCK_LIMIT_REACHED_FOR_LOAN_TYPE,
  ITEM_HAS_OPEN_LOAN
}
